routes:
  /:
    controller: channel
    template: index
  /gem/:
    template: gem
    data: page.gem
  /jasenyys/:
    template: jasenyys
    data: page.jasenyys
  /tili/: tili
    
collections:
  /tapahtunee/:
    permalink: /tapahtunee/{slug}/
    template: tapahtunee
    filter: primary_tag:tapahtunee
  /videot/:
    permalink: /videot/{slug}/
    template: videot
    filter: primary_tag:videot
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /aihe/{slug}/
  author: /kirjoittaja/{slug}/
